app_objs += $(addprefix apps/rpn/,\
  app.o\
  rpn.o\
  rpn_store.o\
  edit_expression_controller.o\
  stack_view_cell.o\
  history_controller.o\
  local_context.o\
  scrollable_expression_view.o\
  selectable_table_view.o\
  text_field.o\
)

tests += $(addprefix apps/rpn/test/,\
  rpn_store.cpp\
)
test_objs += $(addprefix apps/rpn/, rpn.o rpn_store.o)

app_images += apps/rpn/rpn_icon.png

